baseurl = "https://curi0sity.sh"
title = "curi0sity"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "curi0sity"
  info = "Hacking blog"
  description = "Writeups of hackthebox challenges and machines"
  keywords = "blog,developer,personal"
  avatarurl = "/avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]
[caches]
  [caches.images]
    dir = ':cacheDir/images'
    maxAge = "720h"
  [caches.assets]
    dir = ':cacheDir/:project'
    maxAge = "720h"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/curi0sity-sys"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"